### ISSUE TITLE
Инициация интерфейса

### ISSUE THREAD

**Issue by zag7moon** [zag7moon/gitlab-scripts#2]
Создать интерфейс командной строки (CLI) для nodejs приложения, с возможностью:

1. Выбор функции (Удаление пользователя, создание репозитория)
2.1 Удаление пользователя - запрашивается имя пользователя, после подтверждения запускается скрипт удаления
2.1 Создание репозитория - на выбор предлагается:
      - Создать react: https://github.com/SibdevPro/react-typescript-stub
      - Создать vue: **coming soon**
      - Создать django: https://github.com/SibdevPro/backend-stub
      - Создать custom: спрашиваются все необходимые для создания параметры

**Comment by pinkguyius** [comment]
Да, конечно, спасибо за обращение. Можете проверять!
